### ISSUE TITLE
Missing NVIDIA_DRIVER_CAPABILITIES in final jellyfin/jellyfin image

### ISSUE THREAD

**Issue by zakame** [jellyfin/jellyfin-metapackages#2]
Congrats for the 10.6.0 release! :tada:  I upgraded from 10.5.5 on Kubernetes almost flawlessly,except for one bit!

While the old `jellyfin/jellyfin:10.5.5` image defines [`NVIDIA_DRIVER_CAPABILITIES` in the environment](https://github.com/jellyfin/jellyfin/blob/0750357916b600a4b4c27bc4babd2adcc6390473/Dockerfile#L25-L26), the new `jellyfin/jellyfin:10.6.0` does not, despite https://github.com/jellyfin/jellyfin-metapackages/blob/4997416c7db38233c174a31f4cb3a8f3000f3dd9/Dockerfile.amd64#L4

This prevents [nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime) (which in my case, via [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin)) to properly set up, ultimately preventing Nvidia GPU transcodes like so:

```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_cuvid) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (copy)
...
Cannot load libnvcuvid.so.1
[h264_cuvid @ 0xdeadbeef] Failed loading nvcuvid.
```

Easy workaround for now is to simply define the environment variable at container run, e.g. under Kubernetes:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  ...
spec:
  ...
  template:
    spec:
      containers:
      - image: jellyfin/jellyfin:10.6.0
        # work around missing capabilities for GPU transcoding
        env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,video,utility"
        ...
```

though I suppose the relevant lines from the old `jellyfin/Dockerfile` could be moved here to `jellyfin-metapackages/Dockerfile.*`, right?  If so, I can probably whip up a quick PR...

**Comment by delta-whiplash** [comment]
hello someone can explain or just share me his Deployment manifest for jellyfin with nvidia GPU transcoding I want to learn how to do this

**Comment by zakame** [comment]
Hey @delta-whiplash, I still have largely the same Deployment above - what issue are you experiencing?

Also note that you will need to request the `nvidia.com/gpu` resource along with setting the environment variable above - this resource should be available for you when you've installed the gpu-operator.  Your manifest should look like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  ...
spec:
  ...
  template:
    spec:
      containers:
      - image: jellyfin/jellyfin:10.8.9
        # ensure ffmpeg can pick up the needed CUDA libraries
        lifecycle:
          postStart:
            exec:
              command:
              - /sbin/ldconfig
        # ensure capabilities for GPU transcoding
        env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,video,utility"
        ...
        # schedule only if we have GPU resource in cluster
        resources:
          limits:
            nvidia.com/gpu: '1'
          requests:
            nvidia.com/gpu: '1'
      ...
```
